# Generated by Django 6.0.3 on 2026-04-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alunos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('senha', models.CharField(blank=True, max_length=200, null=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('data_matricula', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alunos',
            },
        ),
    ]
