# Generated by Django 6.0.3 on 2026-04-10 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('grupo_muscular', models.CharField(choices=[('Membros Superiores', 'Membros Superiores'), ('Músculos do Tórax e Abdômen', 'Músculos do Tórax e Abdômen'), ('Membros Inferiores', 'Membros Inferiores')], max_length=100)),
            ],
            options={
                'db_table': 'exercicios',
            },
        ),
        migrations.CreateModel(
            name='funcionarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(choices=[('instrutor', 'instrutor'), ('recepcionista', 'recepcionista'), ('administrador', 'administrador')], max_length=20)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('senha', models.CharField(blank=True, max_length=200, null=True)),
                ('turno', models.CharField(choices=[('matutino', 'matutino'), ('vespertino', 'vespertino')], max_length=20)),
            ],
            options={
                'db_table': 'funcionarios',
            },
        ),
        migrations.CreateModel(
            name='fichas_treino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('divisao', models.CharField(choices=[('ABC', 'ABC'), ('ABCD', 'ABCD'), ('ABCDE', 'ABCDE'), ('FULL BODY', 'FULL BODY')], max_length=20)),
                ('grupo', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('FULL BODY', 'FULL BODY')], max_length=20, null=True)),
                ('nivel', models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado'), ('Personalizado', 'Personalizado')], max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('fk_aluno', models.ForeignKey(db_column='fk_aluno', on_delete=django.db.models.deletion.CASCADE, to='alunos.alunos')),
                ('fk_funcionario', models.ForeignKey(db_column='fk_funcionario', on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionarios')),
            ],
            options={
                'db_table': 'fichas_treino',
            },
        ),
        migrations.CreateModel(
            name='listas_exercicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repeticoes', models.IntegerField()),
                ('series', models.IntegerField()),
                ('fk_exercicio', models.ForeignKey(db_column='fk_exercicio', on_delete=django.db.models.deletion.CASCADE, to='funcionarios.exercicios')),
                ('fk_ficha', models.ForeignKey(db_column='fk_ficha', on_delete=django.db.models.deletion.CASCADE, to='funcionarios.fichas_treino')),
            ],
            options={
                'db_table': 'listas_exercicios',
            },
        ),
        migrations.CreateModel(
            name='pagamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('forma_pagamento', models.CharField(choices=[('Cartão Crédito', 'Cartão Crédito'), ('Cartão Débito', 'Cartão Débito'), ('Pix', 'Pix'), ('Dinheiro', 'Dinheiro')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('data_vencimento', models.DateField()),
                ('fk_aluno', models.ForeignKey(db_column='fk_aluno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.alunos')),
            ],
            options={
                'db_table': 'pagamentos',
            },
        ),
    ]
