# Generated by Django 6.0.3 on 2026-03-09 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alunos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('sexo', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1)),
                ('senha', models.CharField(blank=True, max_length=200, null=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('data_matricula', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alunos',
            },
        ),
        migrations.CreateModel(
            name='exercicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('grupo_muscular', models.CharField(choices=[('Membros Superiores', 'Membros Superiores'), ('Músculos do Tórax e Abdômen', 'Músculos do Tórax e Abdômen'), ('Membros Inferiores', 'Membros Inferiores')], max_length=100)),
            ],
            options={
                'db_table': 'exercicios',
            },
        ),
        migrations.CreateModel(
            name='funcionarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(choices=[('instrutor', 'instrutor'), ('recepcionista', 'recepcionista'), ('administrador', 'administrador')], max_length=20)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('senha', models.CharField(blank=True, max_length=200, null=True)),
                ('turno', models.CharField(choices=[('matutino', 'matutino'), ('vespertino', 'vespertino')], max_length=20)),
            ],
            options={
                'db_table': 'funcionarios',
            },
        ),
        migrations.CreateModel(
            name='fichas_treino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('divisao', models.CharField(choices=[('ABC', 'ABC'), ('ABCD', 'ABCD'), ('ABCDE', 'ABCDE'), ('FULL BODY', 'FULL BODY')], max_length=20)),
                ('grupo', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('FULL BODY', 'FULL BODY')], max_length=20, null=True)),
                ('nivel', models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado'), ('Personalizado', 'Personalizado')], max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('fk_aluno', models.ForeignKey(db_column='fk_aluno', on_delete=django.db.models.deletion.CASCADE, to='sistema.alunos')),
                ('fk_funcionario', models.ForeignKey(db_column='fk_funcionario', on_delete=django.db.models.deletion.CASCADE, to='sistema.funcionarios')),
            ],
            options={
                'db_table': 'fichas_treino',
            },
        ),
        migrations.CreateModel(
            name='lista_exercicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repeticoes', models.IntegerField()),
                ('series', models.IntegerField()),
                ('fk_exercicio', models.ForeignKey(db_column='fk_exercicio', on_delete=django.db.models.deletion.CASCADE, to='sistema.exercicios')),
                ('fk_ficha', models.ForeignKey(db_column='fk_ficha', on_delete=django.db.models.deletion.CASCADE, to='sistema.fichas_treino')),
            ],
            options={
                'db_table': 'lista_exercicios',
            },
        ),
    ]
