# Generated by Django 6.0.3 on 2026-03-15 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='pagamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('forma_pagamento', models.CharField(choices=[('Cartão', 'Cartão'), ('Pix', 'Pix'), ('Dinheiro', 'Dinheiro')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('data_vencimento', models.DateField()),
                ('fk_aluno', models.ForeignKey(db_column='fk_aluno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.alunos')),
            ],
            options={
                'db_table': 'pagamentos',
            },
        ),
    ]
