# Generated by Django 6.0.3 on 2026-03-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alunos_ativo_pagamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='ativo',
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='forma_pagamento',
            field=models.CharField(choices=[('Cartão Crédito', 'Cartão Crédito'), ('Cartão Débito', 'Cartão Débito'), ('Pix', 'Pix'), ('Dinheiro', 'Dinheiro')], max_length=20),
        ),
    ]
