# Generated by Django 6.0.3 on 2026-03-16 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_remove_alunos_ativo_alter_pagamentos_forma_pagamento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lista_exercicios',
            new_name='listas_exercicios',
        ),
        migrations.AlterModelTable(
            name='listas_exercicios',
            table='listas_exercicios',
        ),
    ]
