# Generated by Django 6.0.3 on 2026-04-10 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_rename_lista_exercicios_listas_exercicios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichas_treino',
            name='fk_aluno',
        ),
        migrations.RemoveField(
            model_name='listas_exercicios',
            name='fk_exercicio',
        ),
        migrations.RemoveField(
            model_name='fichas_treino',
            name='fk_funcionario',
        ),
        migrations.RemoveField(
            model_name='listas_exercicios',
            name='fk_ficha',
        ),
        migrations.DeleteModel(
            name='pagamentos',
        ),
        migrations.DeleteModel(
            name='alunos',
        ),
        migrations.DeleteModel(
            name='exercicios',
        ),
        migrations.DeleteModel(
            name='funcionarios',
        ),
        migrations.DeleteModel(
            name='fichas_treino',
        ),
        migrations.DeleteModel(
            name='listas_exercicios',
        ),
    ]
